apiVersion: v1
kind: Service
metadata:
  name: nginx-service-webtransactions
  annotations:
    thousandeyes.devnet.cisco.com/test-type: web-transactions
    thousandeyes.devnet.cisco.com/test-spec: |
      import { By, Key } from 'selenium-webdriver';
      import { driver, test } from 'thousandeyes';

      runScript();

      async function runScript() {

          await configureDriver();

          const settings = test.getSettings();

          // Load page
          await driver.get(settings.url);

          await click(By.id(`offer-getstarted`));

      }

      async function configureDriver() {
          await driver.manage().setTimeouts({
              implicit: 7 * 1000, // If an element is not found, reattempt for this many milliseconds
          });
      }

      async function click(selector) {
          await simulateHumanDelay();

          const configuredTimeouts = await driver.manage().getTimeouts();
          const clickAttemptEndTime = Date.now() + configuredTimeouts.implicit;

          await reattemptUntil(attemptToClick, clickAttemptEndTime);

          async function attemptToClick() {
              await driver.findElement(selector)
                          .click();
          }
      }

      async function reattemptUntil(attemptActionFn, attemptEndTime) {
          const TIME_BETWEEN_ATTEMPTS = 100;
          let numberOfAttempts = 0;
          let attemptError;
          while (Date.now() < attemptEndTime || numberOfAttempts === 0) {
              try {
                  numberOfAttempts += 1;
                  await attemptActionFn();
              }
              catch (error) {
                  attemptError = error;
                  await driver.sleep(TIME_BETWEEN_ATTEMPTS);
                  continue; // Attempt failed, reattempt
              }
              attemptError = null;
              break; // Attempt succeeded, stop attempting
          }

          const wasAttemptSuccessful = !attemptError;
          if (!wasAttemptSuccessful) {
              throw attemptError;
          }
      }

      async function simulateHumanDelay() {
          await driver.sleep(5500);
      }
  labels:
    run: nginx
spec:
  selector:
    run: nginx
  ports:
    - port: 80
      protocol: TCP
